apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"8"},"creationTimestamp":"2020-09-18T20:11:57Z","generation":11,"labels":{"app":"racetracker"},"name":"racetracker","namespace":"default","resourceVersion":"42565737","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/racetracker","uid":"3417d334-f9eb-11ea-94d6-42010a9a0113"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"racetracker"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"100%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"racetracker"}},"spec":{"containers":[{"image":"eu.gcr.io/rsyc-257718/racetracker@sha256:b31246677cab58a9435b28b799663cdd60af154d507ad7a1fde1c781bc849219","imagePullPolicy":"IfNotPresent","name":"racetracker-sha256-1","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/app/data","name":"data"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"data","persistentVolumeClaim":{"claimName":"data"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2020-09-18T20:12:06Z","lastUpdateTime":"2020-09-18T20:12:06Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2020-09-18T20:11:57Z","lastUpdateTime":"2020-10-01T20:13:15Z","message":"ReplicaSet \"racetracker-5f74f57c4c\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":11,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2020-09-18T20:11:57Z"
  generation: 12
  labels:
    app: racetracker
  name: racetracker
  namespace: default
  resourceVersion: "42571098"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/racetracker
  uid: 3417d334-f9eb-11ea-94d6-42010a9a0113
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: racetracker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: racetracker
    spec:
      containers:
      - image: eu.gcr.io/rsyc-257718/racetracker:latest
        imagePullPolicy: IfNotPresent
        name: racetracker-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
status:
  conditions:
  - lastTransitionTime: "2020-09-18T20:12:06Z"
    lastUpdateTime: "2020-09-18T20:12:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-09-18T20:11:57Z"
    lastUpdateTime: "2020-10-01T20:33:15Z"
    message: ReplicaSet "racetracker-57fb969b6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 12
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
